### ISSUE TITLE
I18n Library

### ISSUE THREAD

**Issue by roine** [ourveryown/ts-react-boiler#2]
## Why?
Moving from a non-i18n compliant app to a compliant one takes long and is error-prone (forgotten strings). Even though our application will start only in english it is good practice to use i18n early on. 

## Effort
The effort required is small, we'll need to install and use the library and maintain a good structure for the dictionary - the structure could follow that of the application (domains, components).

## Resources
Popular I18n libraries for react are [react-intl][] and [react-i18next][].
Some good practice when manipulating dictionaries (it's for rails but it's some of it is also applicable to JS): [How to organise i18n without losing your translation_not_found ][i18n-dict]

[react-intl]: https://github.com/yahoo/react-intl
[react-i18next]: https://github.com/i18next/react-i18next
[i18n-dict]: https://webuild.envato.com/blog/how-to-organise-i18n-without-losing-your-translation-not-found/

**Comment by jacksonzal** [comment]
i18n has been implemented using the react-i18next library
